BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "HOTEL" (
	"HOTEL_ID"	CHAR(10),
	"HOTEL_NAME"	CHAR(30) NOT NULL,
	"HOTEL_ADDRESS"	VARCHAR(50) NOT NULL,
	"HOTEL_COUNTRY"	CHAR(20) NOT NULL,
	"HOTEL_PHONENO"	INT NOT NULL,
	"HOTEL_DESCRIPTION"	VARCHAR(50) NOT NULL,
	CONSTRAINT "PK_HOTEL_ID" PRIMARY KEY("HOTEL_ID")
);
CREATE TABLE IF NOT EXISTS "FACILITY_TYPE" (
	"FACILITY_TYPE_ID"	CHAR(10),
	"FACILITY_TYPE_NAME"	VARCHAR(20) NOT NULL,
	"FACILITY_TYPE_DESC"	VARCHAR(50) NOT NULL,
	"CAPACITY"	INT NOT NULL CHECK("CAPACITY" > 0),
	"BASE_COST"	DECIMAL(7, 2) NOT NULL CHECK("BASE_COST" > 0),
	"COST_PERIOD"	DECIMAL(7, 2) NOT NULL CHECK("COST_PERIOD" > 0),
	CONSTRAINT "PK_FACILITY_TYPE_ID" PRIMARY KEY("FACILITY_TYPE_ID")
);
CREATE TABLE IF NOT EXISTS "FACILITY" (
	"FACILITY_ID"	CHAR(10),
	"FACILITY_NAME"	CHAR(20) NOT NULL,
	"FACILITY_DESC"	VARCHAR(50) NOT NULL,
	"FACILITY_STATUS"	CHAR(20) NOT NULL,
	"HOTEL_ID"	CHAR(10) NOT NULL,
	CONSTRAINT "PK_FACILITY_ID" PRIMARY KEY("FACILITY_ID"),
	CONSTRAINT "FK_HOTEL_ID" FOREIGN KEY("HOTEL_ID") REFERENCES "HOTEL"("HOTEL_ID")
);
CREATE TABLE IF NOT EXISTS "SERVICE_CATEGORY" (
	"SERVICE_CATEGORY_ID"	CHAR(10),
	"SERVICE_CATEGORY_NAME"	CHAR(20) NOT NULL,
	"SERVICE_CATEGORY_DESC"	VARCHAR(50) NOT NULL,
	"SERVICE_CATEGORY_TYPE"	CHAR(20) NOT NULL,
	CONSTRAINT "PK_SERVICE_CATEGORY_ID" PRIMARY KEY("SERVICE_CATEGORY_ID")
);
CREATE TABLE IF NOT EXISTS "SERVICE" (
	"SERVICE_ID"	CHAR(10),
	"SERVICE_NAME"	CHAR(20) NOT NULL,
	"SERVICE_DESC"	VARCHAR(100) NOT NULL,
	"SERVICE_RESTRICTIONS"	VARCHAR(100) NOT NULL,
	"SERVICE_NOTES"	VARCHAR(100) NOT NULL,
	"SERVICE_COMMENTS"	VARCHAR(100) NOT NULL,
	"SERVICE_STATUS"	CHAR(20) NOT NULL,
	"AVAILABLE_TIMES"	TIME NOT NULL,
	"SERVICE_CAPACITY"	INT NOT NULL CHECK("SERVICE_CAPACITY" > 0),
	"SERVICE_CATEGORY_ID"	CHAR(10) NOT NULL,
	"HOTEL_ID1"	CHAR(10) NOT NULL,
	CONSTRAINT "PK_SERVICE_ID" PRIMARY KEY("SERVICE_ID"),
	CONSTRAINT "FK_SERVICE_CATEGORY_ID" FOREIGN KEY("SERVICE_CATEGORY_ID") REFERENCES "SERVICE_CATEGORY"("SERVICE_CATEGORY_ID"),
	CONSTRAINT "FK_HOTEL_ID1" FOREIGN KEY("HOTEL_ID1") REFERENCES "HOTEL"("HOTEL_ID")
);
CREATE TABLE IF NOT EXISTS "ADVERTISEMENT" (
	"ADVERTISEMENT_ID"	INT,
	"ADVERTISEMENT_NAME"	CHAR(100) NOT NULL,
	"ADV_DESC"	VARCHAR(100) NOT NULL,
	"START_DATE"	DATETIME NOT NULL,
	"END_DATE"	DATETIME NOT NULL,
	"PRICE"	DECIMAL(7, 2) NOT NULL CHECK("PRICE" > 0),
	"INCLUSIONS"	VARCHAR(100) NOT NULL,
	"EXCLUSIONS"	VARCHAR(100) NOT NULL,
	"STATUS"	CHAR(10) NOT NULL,
	CONSTRAINT "PK_ADVERTISEMENT_ID" PRIMARY KEY("ADVERTISEMENT_ID")
);
CREATE TABLE IF NOT EXISTS "ADV_PACKAGE" (
	"ADV_PACKAGE_ID"	INT,
	"ADVERTISEMENT_ID"	INT NOT NULL,
	CONSTRAINT "PK_ADV_PACKAGE_ID" PRIMARY KEY("ADV_PACKAGE_ID"),
	CONSTRAINT "FK_ADVERTISEMENT_ID" FOREIGN KEY("ADVERTISEMENT_ID") REFERENCES "ADVERTISEMENT"("ADVERTISEMENT_ID")
);
CREATE TABLE IF NOT EXISTS "ADV_SERVICE" (
	"ADV_SERVICE_ID"	INT,
	"ADVERTISEMENT_ID1"	INT NOT NULL,
	CONSTRAINT "PK_ADV_SERVICE_ID" PRIMARY KEY("ADV_SERVICE_ID"),
	CONSTRAINT "FK_ADVERTISEMENT_ID1" FOREIGN KEY("ADVERTISEMENT_ID1") REFERENCES "ADVERTISEMENT"("ADVERTISEMENT_ID")
);
CREATE TABLE IF NOT EXISTS "PACKAGE_SERVICE" (
	"ADVERTISEMENT_ID1"	INT,
	"SERVICE_ID"	CHAR(10) NOT NULL,
	CONSTRAINT "PK_ADVERTISEMENT_ID1" PRIMARY KEY("ADVERTISEMENT_ID1"),
	CONSTRAINT "FK_SERVICE_ID" FOREIGN KEY("SERVICE_ID") REFERENCES "SERVICE"("SERVICE_ID")
);
CREATE TABLE IF NOT EXISTS "RELATION_FACILITYTYPE_SERVICE" (
	"FACILITY_TYPE"	CHAR(10),
	"SERVICE_ID1"	CHAR(10),
	CONSTRAINT "PK_FACILITY_TYPE" PRIMARY KEY("FACILITY_TYPE"),
	CONSTRAINT "FK_SERVICE_ID1" FOREIGN KEY("SERVICE_ID1") REFERENCES "SERVICE"("SERVICE_ID")
);
CREATE TABLE IF NOT EXISTS "CUSTOMER" (
	"CUSTOMER_ID"	CHAR(10),
	"CUSTOMER_NAME"	CHAR(20) NOT NULL,
	"CUSTOMER_ADDRESS"	VARCHAR(50) NOT NULL,
	"CUSTOMER_PHONENO"	INT NOT NULL,
	"CUSTOMER_COUNTRY"	CHAR(20) NOT NULL,
	"CUSTOMER_EMAIL_ADDRESS"	VARCHAR(50) NOT NULL,
	CONSTRAINT "PK_CUSTOMER_ID" PRIMARY KEY("CUSTOMER_ID")
);
CREATE TABLE IF NOT EXISTS "EMPLOYEE" (
	"EMPLOYEE_ID"	CHAR(10),
	"EMPLOYEE_NAME"	CHAR(20) NOT NULL,
	"EMPLOYEE_PHONENO"	INT NOT NULL,
	"EMPLOYEE_EMAIL_ADDRESS"	VARCHAR(50) NOT NULL,
	"EMPLOYEE_POSITION"	CHAR(20) NOT NULL,
	CONSTRAINT "PK_EMPLOYEE_ID" PRIMARY KEY("EMPLOYEE_ID")
);
CREATE TABLE IF NOT EXISTS "RESERVATION" (
	"RESERVATION_ID"	CHAR(10),
	"R_NAME"	CHAR(20) NOT NULL,
	"R_STATUS"	CHAR(20) NOT NULL,
	"R_TYPE"	CHAR(20) NOT NULL,
	"R_PLACEDATETIME"	DATETIME NOT NULL,
	"R_DISCOUNT_PERCENTAGE"	INT NOT NULL,
	"R_DESCRIPTION"	VARCHAR(50) NOT NULL,
	"CUSTOMER_ID"	CHAR(10),
	"EMPLOYEE_ID"	CHAR(10),
	CONSTRAINT "PK_RESERVATION_ID" PRIMARY KEY("RESERVATION_ID"),
	CONSTRAINT "FK_EMPLOYEE_ID" FOREIGN KEY("EMPLOYEE_ID") REFERENCES "EMPLOYEE"("EMPLOYEE_ID"),
	CONSTRAINT "FK_CUSTOMER_ID" FOREIGN KEY("CUSTOMER_ID") REFERENCES "CUSTOMER"("CUSTOMER_ID")
);
CREATE TABLE IF NOT EXISTS "BOOKING_DETAILS" (
	"BOOKING_DETAILS_ID"	CHAR(10),
	"BD_START_DATE"	DATETIME NOT NULL,
	"BD_END_DATE"	DATETIME NOT NULL,
	"BD_QUANTITY"	INT NOT NULL CHECK("BD_QUANTITY" > 0),
	"BD_TOTAL_PRICE"	DECIMAL(7, 2) NOT NULL CHECK("BD_TOTAL_PRICE" > 0),
	"ADVERTISEMENT_ID2"	INT,
	"RESERVATION_ID"	CHAR(10),
	CONSTRAINT "PK_BOOKING_DETAILS_ID" PRIMARY KEY("BOOKING_DETAILS_ID"),
	CONSTRAINT "FK_ADVERTISEMENT_ID2" FOREIGN KEY("ADVERTISEMENT_ID2") REFERENCES "ADVERTISEMENT"("ADVERTISEMENT_ID"),
	CONSTRAINT "FK_RESERVATION_ID" FOREIGN KEY("RESERVATION_ID") REFERENCES "RESERVATION"("RESERVATION_ID")
);
CREATE TABLE IF NOT EXISTS "FACILITY_BOOKING" (
	"FACILITY_BOOKING_ID"	INT,
	"FB_NAME"	CHAR(10) NOT NULL,
	"FB_START_DATE"	DATETIME NOT NULL,
	"FB_END_DATE"	DATETIME NOT NULL,
	"FB_DESC"	VARCHAR(100) NOT NULL,
	"FACILITY_ID"	CHAR(10),
	"BOOKING_DETAILS_ID"	CHAR(10),
	CONSTRAINT "FK_BOOKING_DETAILS_ID" FOREIGN KEY("BOOKING_DETAILS_ID") REFERENCES "BOOKING_DETAILS"("BOOKING_DETAILS_ID"),
	CONSTRAINT "FK_FACILITY_ID" FOREIGN KEY("FACILITY_ID") REFERENCES "FACILITY"("FACILITY_ID"),
	CONSTRAINT "PK_FACILITY_BOOKING_ID" PRIMARY KEY("FACILITY_BOOKING_ID")
);
CREATE TABLE IF NOT EXISTS "PAYMENT" (
	"PAYMENT_ID"	INT,
	"P_TYPE"	CHAR(50) NOT NULL,
	"P_TOTAL_PRICE"	DECIMAL(7, 2) NOT NULL,
	"RESERVATION_ID1"	CHAR(10),
	CONSTRAINT "FK_RESERVATION_ID1" FOREIGN KEY("RESERVATION_ID1") REFERENCES "RESERVATION"("RESERVATION_ID"),
	CONSTRAINT "PK_PAYMENT_ID" PRIMARY KEY("PAYMENT_ID")
);
CREATE TABLE IF NOT EXISTS "RELATION_CUSTOMER_BOOKING" (
	"CUSTOMER_ID1"	CHAR(10),
	"BOOKING_DETAILS_ID1"	CHAR(10) NOT NULL,
	"CUSTOMER_ID2"	CHAR(10),
	CONSTRAINT "FK_BOOKING_DETAILS_ID1" FOREIGN KEY("BOOKING_DETAILS_ID1") REFERENCES "BOOKING_DETAILS"("BOOKING_DETAILS_ID"),
	CONSTRAINT "FK_CUSTOMER_ID1" FOREIGN KEY("CUSTOMER_ID2") REFERENCES "CUSTOMER"("CUSTOMER_ID"),
	CONSTRAINT "PK_CUSTOMER_ID1" PRIMARY KEY("CUSTOMER_ID1")
);
CREATE TABLE IF NOT EXISTS "OTHERCHARGES" (
	"OTHERCHARGES_ID"	CHAR(10),
	"OC_NAME"	CHAR(50) NOT NULL,
	"OC_TYPE"	CHAR(50) NOT NULL,
	"OC_PRICE"	DECIMAL(7, 2) NOT NULL,
	"BOOKING_DETAILS_ID2"	CHAR(10) NOT NULL,
	CONSTRAINT "FK_BOOKING_DETAILS_ID2" FOREIGN KEY("BOOKING_DETAILS_ID2") REFERENCES "BOOKING_DETAILS"("BOOKING_DETAILS_ID"),
	CONSTRAINT "PK_OTHERCHARGES_ID" PRIMARY KEY("OTHERCHARGES_ID")
);
COMMIT;
